#define SERV_PORT	5193
#define BACKLOG		10
#define MAXLINE		1024

#define BUFFER_READ_FILE_DIMENSION 16384
#define MAX_PK_DATA_SIZE 512

#define WIN_DIMENSION 2

#define LOSS_PROBABILITY 0

#define SERVER_SHARE_PATH "/home/marco/share/"

#define FILES_ONLY 1